INSERT INTO cadastro.cidade (nome, uf) VALUES ('Abdon Batista','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Abelardo Luz','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Agrolândia','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Agronômica','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Água Doce','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Águas de Chapecó','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Águas Frias','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Águas Mornas','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Alfredo Wagner','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Alto Bela Vista','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Anchieta','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Angelina','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Anita Garibaldi','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Anitápolis','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Antônio Carlos','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Apiúna','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Arabutã','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Araquari','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Araranguá','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Armazém','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Arroio Trinta','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Arvoredo','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Ascurra','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Atalanta','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Aurora','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Balneário Arroio do Silva','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Balneário Camboriú','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Balneário Barra do Sul','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Balneário Gaivota','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Bandeirante','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Barra Bonita','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Barra Velha','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Bela Vista do Toldo','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Belmonte','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Benedito Novo','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Biguaçu','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Blumenau','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Bocaina do Sul','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Bombinhas','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Bom Jardim da Serra','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Bom Jesus','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Bom Jesus do Oeste','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Bom Retiro','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Botuverá','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Braço do Norte','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Braço do Trombudo','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Brunópolis','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Brusque','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Caçador','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Caibi','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Calmon','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Camboriú','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Capão Alto','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Campo Alegre','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Campo Belo do Sul','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Campo Erê','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Campos Novos','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Canelinha','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Canoinhas','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Capinzal','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Capivari de Baixo','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Catanduvas','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Caxambu do Sul','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Celso Ramos','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Cerro Negro','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Chapadão do Lageado','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Chapecó','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Cocal do Sul','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Concórdia','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Cordilheira Alta','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Coronel Freitas','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Coronel Martins','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Corupá','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Correia Pinto','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Criciúma','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Cunha Porã','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Cunhataí','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Curitibanos','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Descanso','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Dionísio Cerqueira','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Dona Emma','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Doutor Pedrinho','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Entre Rios','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Ermo','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Erval Velho','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Faxinal dos Guedes','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Flor do Sertão','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Florianópolis','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Formosa do Sul','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Forquilhinha','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Fraiburgo','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Frei Rogério','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Galvão','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Garopaba','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Garuva','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Gaspar','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Governador Celso Ramos','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Grão Pará','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Gravatal','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Guabiruba','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Guaraciaba','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Guaramirim','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Guarujá do Sul','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Guatambú','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Herval do Oeste','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Ibiam','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Ibicaré','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Ibirama','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Içara','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Ilhota','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Imaruí','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Imbituba','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Imbuia','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Indaial','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Iomerê','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Ipira','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Iporã do Oeste','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Ipuaçu','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Ipumirim','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Iraceminha','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Irani','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Irati','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Irineópolis','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Itá','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Itaiópolis','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Itajaí','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Itapema','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Itapiranga','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Itapoá','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Ituporanga','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Jaborá','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Jacinto Machado','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Jaguaruna','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Jaraguá do Sul','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Jardinópolis','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Joaçaba','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Joinville','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('José Boiteux','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Jupiá','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Lacerdópolis','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Lages','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Laguna','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Lajeado Grande','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Laurentino','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Lauro Muller','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Lebon Régis','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Leoberto Leal','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Lindóia do Sul','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Lontras','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Luiz Alves','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Luzerna','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Macieira','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Mafra','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Major Gercino','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Major Vieira','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Maracajá','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Maravilha','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Marema','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Massaranduba','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Matos Costa','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Meleiro','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Mirim Doce','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Modelo','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Mondaí','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Monte Carlo','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Monte Castelo','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Morro da Fumaça','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Morro Grande','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Navegantes','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Nova Erechim','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Nova Itaberaba','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Nova Trento','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Nova Veneza','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Novo Horizonte','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Orleans','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Otacílio Costa','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Ouro','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Ouro Verde','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Paial','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Painel','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Palhoça','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Palma Sola','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Palmeira','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Palmitos','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Papanduva','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Paraíso','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Passo de Torres','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Passos Maia','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Paulo Lopes','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Pedras Grandes','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Penha','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Peritiba','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Pescaria Brava','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Petrolândia','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Balneário Piçarras','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Pinhalzinho','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Pinheiro Preto','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Piratuba','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Planalto Alegre','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Pomerode','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Ponte Alta','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Ponte Alta do Norte','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Ponte Serrada','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Porto Belo','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Porto União','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Pouso Redondo','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Praia Grande','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Presidente Castello Branco','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Presidente Getúlio','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Presidente Nereu','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Princesa','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Quilombo','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Rancho Queimado','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Rio das Antas','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Rio do Campo','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Rio do Oeste','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Rio dos Cedros','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Rio do Sul','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Rio Fortuna','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Rio Negrinho','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Rio Rufino','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Riqueza','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Rodeio','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Romelândia','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Salete','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Saltinho','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Salto Veloso','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Sangão','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Santa Cecília','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Santa Helena','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Santa Rosa de Lima','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Santa Rosa do Sul','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Santa Terezinha','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Santa Terezinha do Progresso','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Santiago do Sul','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Santo Amaro da Imperatriz','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('São Bernardino','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('São Bento do Sul','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('São Bonifácio','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('São Carlos','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('São Cristovão do Sul','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('São Domingos','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('São Francisco do Sul','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('São João do Oeste','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('São João Batista','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('São João do Itaperiú','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('São João do Sul','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('São Joaquim','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('São José','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('São José do Cedro','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('São José do Cerrito','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('São Lourenço do Oeste','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('São Ludgero','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('São Martinho','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('São Miguel da Boa Vista','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('São Miguel do Oeste','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('São Pedro de Alcântara','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Saudades','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Schroeder','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Seara','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Serra Alta','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Siderópolis','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Sombrio','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Sul Brasil','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Taió','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Tangará','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Tigrinhos','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Tijucas','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Timbé do Sul','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Timbó','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Timbó Grande','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Três Barras','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Treviso','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Treze de Maio','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Treze Tílias','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Trombudo Central','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Tubarão','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Tunápolis','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Turvo','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('União do Oeste','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Urubici','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Urupema','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Urussanga','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Vargeão','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Vargem','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Vargem Bonita','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Vidal Ramos','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Videira','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Vitor Meireles','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Witmarsum','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Xanxerê','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Xavantina','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Xaxim','SC');
INSERT INTO cadastro.cidade (nome, uf) VALUES ('Zortéa','SC');